alpha: 0.5
beta: 0.5
device: !!python/object/apply:torch.device
- cpu
eps: 0.001
eval_batch_size: 16
eval_freq: 5000
eval_kernel: rbf
eval_logfile: null
eval_num_batches: 3000
eval_num_bs: 50
eval_num_samples: 50
eval_seed: 0
expconfig: wenc
expid: null
gpu: -1
loc: path1
loss: nll
lr: 0.0005
max_num_points: 50
mode: train
model: np
num_epochs: 100000
plot_batch_size: 16
plot_num_bs: 50
plot_num_ctx: 30
plot_num_samples: 30
plot_num_tar: 10
plot_seed: 0
print_freq: 200
resume: null
root: 1d/np
save_freq: 1000
start_time: null
t_noise: null
task: 1d
train_batch_size: 100
train_num_bs: 10
train_num_samples: 4
train_seed: 0
wagg: mean
wenc: true
wloss: true
yenc: true
